### ISSUE TITLE
Will this work on an RTX 2080 (arch=compute_75)? 

### ISSUE THREAD

**Issue by andrewjong** [RenYurui/Global-Flow-Local-Attention#27]
Hi, thanks for the amazing repository!

I followed the installation instructions and saw the note you made about the `nvcc` flags. I consulted the article you linked, and saw that SM_75 is required for my RTX 2080 GPU. 

So I added
```
'-gencode', 'arch=compute_75,code=sm_75',
'-gencode', 'arch=compute_75,code=compute_75'
```
 to all 3 `setup.py` files and ran `./setup.sh`. 

However, I get this error.

```bash
╰─ python demo.py \                                      
--name=dance_fashion_checkpoints \
--model=dance \
--attn_layer=2,3 \
--kernel_size=2=5,3=3 \
--gpu_id=0 \
--dataset_mode=dance \
--sub_dataset=fashion \
--dataroot=./dataset/danceFashion \
--results_dir=./demo_results/dance_fashion \
--test_list=val_list.csv

dataset [DanceDataset] of size 141 was created
val images = 141
Network [DanceGenerator] was created. Total number of parameters: 23.5102 million. To see the architecture, do print(network).
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/generic/THCTensorMathPairwise.cu line=225 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    model = create_model(opt)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/__init__.py", line 32, in create_model
    instance = model(opt)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/dance_model.py", line 79, in __init__
    norm='instance', activation='LeakyReLU', extractor_kz=opt.kernel_size)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/networks/__init__.py", line 37, in define_g
    return create_network(netG_cls, opt, **parameter_dic)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/networks/__init__.py", line 28, in create_network
    net.init_weights(opt.init_type)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/networks/base_network.py", line 55, in init_weights
    self.apply(init_func)
  File "/home/andrew/.miniconda3/envs/gfla/lib/python3.7/site-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  File "/home/andrew/.miniconda3/envs/gfla/lib/python3.7/site-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  File "/home/andrew/.miniconda3/envs/gfla/lib/python3.7/site-packages/torch/nn/modules/module.py", line 242, in apply
    module.apply(fn)
  [Previous line repeated 1 more time]
  File "/home/andrew/.miniconda3/envs/gfla/lib/python3.7/site-packages/torch/nn/modules/module.py", line 243, in apply
    fn(self)
  File "/home/andrew/Development/Global-Flow-Local-Attention/model/networks/base_network.py", line 47, in init_func
    init.orthogonal_(m.weight.data, gain=gain)
  File "/home/andrew/.miniconda3/envs/gfla/lib/python3.7/site-packages/torch/nn/init.py", line 356, in orthogonal_
    q, r = torch.qr(flattened)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1544176307774/work/aten/src/THC/generic/THCTensorMathPairwise.cu:225
```

This [forum post](https://discuss.pytorch.org/t/cholesky-decomposition-with-cuda/40303/2) leads me to think it may be a CUDA issue (I have CUDA 10.0 installed globally; would this be an issue even if conda installs CUDA 9.0 locally?). In any case, it seems PyTorch 1.0.0 is only compiled with CUDA 9.0 anyway.

My question is, is it possible for this repository to run on an RTX 2080 GPU? Thanks!

**Comment by RenYurui** [comment]
Hi!
Thanks for your interest. 
We have not tried to run our code on an RTX 2080.
However, your modification seems correct.
Our code can run with both CUDA 9 and CUDA 10.
PyTorch 1.0.0 compiled with CUDA 10 can be found [here](https://pytorch.org/get-started/previous-versions/#linux-and-windows-6)

Meanwhile, your error seems not related to the Custom CUDA modules. The error occurs when the model was built. Therefore, please check your environment.

**Comment by andrewjong** [comment]
Cool! I got it to work with CUDA 10. Thanks for reminding me about the PyTorch 1.0.0 w/ CUDA 10 install, I forgot about that.
